### ISSUE TITLE
[Question] Interested in full libical rust rewrite?

### ISSUE THREAD

**Issue by ngortheone** [matthiasbeyer/libical#1]
Hey @matthiasbeyer 

I have a need in `libical` for rust. I noticed your project during research. 
I am interested why did you decide to do a high-level wrapper? 
Would you be interested in joining forces for a full rust rewrite of `libical`?

**Comment by matthiasbeyer** [comment]
Hi!

Awesome that you need something like this, we should definitively join forces!

Well, I did a high-level wrapper around libical-sys which is a rust binding for libical, which is a huge C/C++ library for ical stuff.

I decided to do this because this is the fastest way to get something working. libical is used by big projects like KDE, so it won't go away anytime soon, I suppose. I will have absolutely too little time to actually implement ical myself, it is a huge standard with a lot of fuckery in it (sorry for the language). This is a way to get up and running _fast_. That's what I am looking for.

I would love to join forces with you! But I won't participate in a full rewrite in Rust because that's just too much to do.

**Comment by ngortheone** [comment]
Well, yes, it is not a small project - about 50k lines of C code (including whitespace and comments - `wc -l` basically) but I was inspired by https://github.com/open-i18n/rust-unic - basically an ICU rewrite for rust.

> I would love to join forces with you! But I won't participate in a full rewrite in Rust because that's just too much to do.

If I am to start a rewrite project, what kind of participation would you be interested in?

**Comment by matthiasbeyer** [comment]
If you'd start a rewrite, I wish you best and luck, but I have very little time even for [imag](https://imag-pim.org) so I won't contribute to a full rewrite of libical.

I hope I can provide a high-level wrapper for libical-sys based on the codebase in this repository (see the "extract-libical" branch) soon. The base here is actually pretty good, so I'm rather positive.

**Comment by ngortheone** [comment]
Wow, imag is a cool project. I've been thinking about something like this for a while. Do accept new contributors?

**Comment by matthiasbeyer** [comment]
Of course! Am always looking for new contributors! I guess you wrote to the ML, I'll reply in a bit.

**Comment by matthiasbeyer** [comment]
I'll close this for now, because I do not target a full rewrite here. Hope that's okay with you.
